### PR TITLE
Update Icons

### PR DESCRIPTION
**Pull request by jackhumbert**
The I've included the .ai for these as well. The icon.icns file hasn't been generated yet (don't have access to a Mac right now).

I noticed you have a background for the macOS installation - do you have the installer set to a custom size and everything? I can update that graphic as well. [Here's some more information on the custom finder windows](http://stackoverflow.com/questions/8680132/creating-nice-dmg-installer-for-mac-os-x).

I ended up using [this](http://icoconvert.com/Multi_Image_to_one_icon/) to merge all the .png files into one .ico file.

### CODE REVIEW

**Comment by skullydazed** [comment]
I can't turn these into a mac icon. I'm not sure why, and I can't try exporting in different ways because when I open up psi.ai I get two errors:

* Could not find the linked file "psi-16-psi.png"
* The Constantina font is not available on my computer

For the font issue we should probably convert the letters to shapes, that way we don't have to embed the font in the source file.

I'm also wondering if we want to commit the .ai file, or if we should be using .svg as the primary format. If we use .svg than people who use Inkscape and other vector programs can contribute improvements too.

**Comment by jackhumbert** [comment]
Sorry for that oversight - I've rasterised the linked file, and outlined the text.

Does the icon merging provide any errors? I noticed there were a few more icons (more @2x ones) than what was in the documentation.

I think committing the source file in the original format (.ai in this case) is fine - I mostly committed it so I wouldn't lose it :) Illustrator is pretty standard, and some of the features aren't supported in .svg to my knowledge, and we'd be losing information by converting it.

**Comment by skullydazed** [comment]
It's basically all some variation of this: 

    build/icon.iconset:warning: Missing image for variant named 'ixon' resource error: 'Failed to load image at 512@1x.'.

All the things I've read suggest it's either a naming error or a lack of an alpha channel, but those seem fine in this case. I'm guessing it has something to do with some PNG specific option that was selected, so if I can export files that work I will document the settings.

**Comment by skullydazed** [comment]
OK, looks like iconutil is picky about what files exist, not just the naming for the files it uses. I've documented the easiest export option, and updated the README.md. If it looks good to you we can squash and merge.

**Comment by jackhumbert** [comment]
Ah, gotcha. Nice. Sounds good!

**Pull request merged**
