### PR TITLE
UI improvements, flash-when-ready button, bugfixes, etc.

### LINKED ISSUE #3: Automatic bulk flashing
There should be a special mode that can be enabled that flashes as soon as a the DFU bootloader is detected.

Suggested by IBNobody over on Reddit.

### PR DESCRIPTION
**Pull request by ItsHarper**
### This PR should probably be tested on Mac, both packaged and unpackaged

This pull request turned out to be much larger than expected. Originally it was just going to be a bit of UI tweaking.  I'll try to be detailed about what I changed and why. 

You will need to rerun `npm install` after pulling these changes.

### Changes

These are more-or-less in order of importance. I'm only listing the bugfixes for bugs that existed outside of this branch.

* **Fixed critical bugs with finding dfu-programmer in packaged mode**
See [this commit](https://github.com/jackhumbert/qmk_firmware_flasher/commit/2eb7f5dc54e869f0451b7b6ed78c1feb2b5e794e) and [this commit](https://github.com/jackhumbert/qmk_firmware_flasher/commit/b5f6b342efbb2e5e6b96d970fcd97bb2a15a2a8e). 

* **Added a button to flash the firmware once the reset button is pressed**
Closes #3. The button only appears once a hex file has been loaded. If a dfu mode device is detected, it will always disappear.

* **The flash button no longer turns red** 
The state of the UI after flashing felt like it was sending a mixed message. The text said it was successful, but then there was a big red thing that could be  interpreted as a failure at first glance. Originally, I was going to add a third state, where the button would be green but grayed out after a successful flash, but to me it made more sense to stick with just two. So now the button is always green, and gets grayed out a bit when disabled. This also fits better with convention. 

* **Bootstrap now handles the styling of the flash button**
This makes it really simple to do things like gray out the button once it's disabled. Yes, the button looks a bit different, but I for one think it's an improvement.

* **Made the window a bit smaller on Windows**
Things line up much better now.

* **If dfu-programmer isn't running correctly on 32-bit Windows, assume it is due to [this issue](https://github.com/dfu-programmer/dfu-programmer/issues/35) and display an appropriate, more helpful error**

* **Added a packaging script for Windows that can actually run on Windows**

* **The app now tests for a dfu mode device every 5 seconds, down from 10**

* **Added electron-debug to the project**
This will only have an affect when you are running directly from the source code. It enables things like keyboard shortcuts to pull up the developer tools. See [this page](https://www.npmjs.com/package/electron-debug) for more details.

* **Updated Bootstrap to version 3 and opted to obtain it via npm rather than including it directly in the repo**
Buttons in Bootstrap 3 look much nicer than ones in Bootstrap 2. Updating will also be much easier in the future.

* **The results of JQuery selectors now get cached to variables** 
This is good for performance, but I mostly did it because the JQuery syntax is ugly.

* **The menubar no longer shows up when running from source**

* **Removed some code related to buttons that no longer exist**

### CODE REVIEW

**Comment by ItsHarper** [comment]
Screenshots:

image

image

image

**Comment by ItsHarper** [comment]
I'm going to go ahead and submit new, smaller, easier to review pull requests in place of this one.

**Comment by skullydazed** [comment]
There's no need for that. Sorry I missed this, sometimes I get overwhelmed by all the QMK email that doesn't pertain to me. :) I have a full day today but I should be able to review this by the end of the weekend.

**Comment by ItsHarper** [comment]
OK, fair enough :)

**Comment by ItsHarper** [comment]
The 32-bit thing was a misdiagnosis. Working on a fix.

**Comment by ItsHarper** [comment]
@skullydazed Do you have any idea why the installer won't install the driver on a completely fresh Windows 7 x64 VM, or what I could try to figure it out? The command isn't giving any output as displayed  in my most recent commit. When the driver installs correctly, it does show the expected output in the installer log.

**Comment by skullydazed** [comment]
I wish I had an answer for that one. I've never been able to get it to fail, either in a VM or booted directly. Yet you (and others) seem to have the problem constantly. I don't know why, and if there's an alternate method we can try for installing the driver I'm all for it.

**Comment by ItsHarper** [comment]
I think I might take a crack at rewriting the installer with [Wix Tooolset](http://wixtoolset.org/). It has a dedicated driver installation module. The driver installation issue isn't related to this though. For now, I'll just revert the one commit and make a couple of new issues.

**Comment by skullydazed** [comment]
I did some basic checking over of both this and your wix branch and so far it's all looking good. I can run it in dev mode on my mac still and I built both windows (NSIS) and mac packages. Tomorrow I'll try to find some time to fire up a windows box and try building with wix myself.

**Comment by ItsHarper** [comment]
Good to hear. 

I just pushed my latest changes to the wix branch. It still needs work, but it now produces a single .exe instead of two .msi files.

**Comment by skullydazed** [comment]
I feel like I'm going crazy here. :) Last night I had the flash when ready button, but this morning it's vanished after I changed branches a couple times. On both the "wix-installer" and "improve-button-behavior" branch it's gone. Any idea what's going on?

The more I work with it the more I dislike how the flash button operates. The change is too subtle and still being green when we're not ready to flash sends a mixed message as well. What if that went back to the old behavior, only instead of red it was grey on grey? That way it's obvious it's disabled but you don't have the red shouting "something is wrong!" after a successful flash.

**Comment by ItsHarper** [comment]
The flash when ready button only shows up when you have a hex file loaded but no dfu device detected. You're sure you're hitting that condition?

Sure, I'll play with the styling and get rid of the green in disabled mode. I agree that gray may be a better choice.

**Comment by skullydazed** [comment]
Ahha, that was it. I had left my test keyboard plugged in and in dfu mode. This will work in the meantime, but longer term I'd like to find a more discoverable way to expose that. That may require waiting until we implement more features so we can collect those into a dedicated section.

**Comment by ItsHarper** [comment]
Why? If your keyboard is ready to be flashed, than a flash-when-ready button does the same thing as a flash now button. This is the type of behavior that IMO _should_ be hidden, if the user doesn't need it.

**Comment by skullydazed** [comment]
People may not even realize it exists if they're in the habit of hitting reset and then loading the hex file. While that's not a flow we promote with the UI it's a perfectly cromulent use case. I think there's also a good argument that you should be able to toggle that on even when a hex isn't loaded. What if a user wants to turn that on before loading a hex?

But none of that should stop the feature from shipping now. This is useful and I think we should get it out there.

**Comment by ItsHarper** [comment]
Putting the device in dfu mode, loading the hex file, and hitting the flash button is a perfectly natural flow. There's nothing confusing or inconvenient about it. So why do they need to know that a button (that in their case won't even do anything different than the button they do see) exists?

I'm a little mixed on showing flash-when-ready before a hex is loaded, but I'm open to it when you put it that way. Which is funny, because it's really the same thing as above. The button would just mean "flash when hex is loaded" instead of "flash when device detected".

My main concern with it is that  could introduce some confusion with what "ready" means. Right now, flash when ready shows up when the app is saying "put your keyboard in reset mode", and that's' the only thing it's waiting on. I think it could be a little confusing to have it mean "put your keyboard in reset mode AND load a hex file" when the app is only saying to load the hex file.  Yes, we could modify the display text on start to indicate that the hex file needs to be loaded and that the keyboard needs to be plugged in and in reset mode. But I'm not sure what I think about that. I kind of like our current straightforward one-step-at-a-time approach.

Also, IMO the main reason we need a flash-when-ready button is because it can take a while for Windows to detect the device, install the driver, and then for our app to detect the device. We don't want to make the user hold their finger over the button while all of that happens. But loading a hex file doesn't have that problem. There's really no benefit to clicking flash before you load the hex file instead of after. Also, what if the user loads the wrong hex file? If they have the device in dfu mode already, it would flash before they had a chance to pick the right one.

So yeah, I'm actually still pretty opposed to showing the FWR button before the hex is loaded, though I'm always open to having my mind changed.

**Comment by skullydazed** [comment]
One of the intents behind #3 is to make it easy to flash several PCB's at once. (The teensy flasher's automatic flash checkbox works this way.) When I order 5-10 PCB's from circuithub, for example, I don't pay for flashing so the PCB's start in DFU mode. I would expect that once I click the "flash when ready" button, it will flash whenever it detects that all conditions are good for flashing. I'd expect that state will be maintained if I load a different hex file, or after flashing another keyboard. Perhaps even after restarting the program.

From that perspective, it seems unusual that I can only enable that state if I remember to load the hex before I plug in my first pcb.

**Comment by ItsHarper** [comment]
Ohhh, you're talking about an entirely different (and far more exotic) use-case than I was envisioning. I'll think about that more after I finish and push the new disabled button styling. I think you'll like it.

**Comment by skullydazed** [comment]
Sounds good. I think we're having a good conversation about #3 here, and should move it over into that issue so we don't clutter up this PR.

**Comment by ItsHarper** [comment]
Agreed.

**Comment by ItsHarper** [comment]
See what you think of that.

**Comment by skullydazed** [comment]
Nice, that's perfect for the flash button.

**Comment by ItsHarper** [comment]
There's your edge case fix

**Comment by skullydazed** [comment]
Any other changes you want to make, or is this ready to merge? I just read through the complete diff and everything looks good to me.

**Comment by ItsHarper** [comment]
Let's do it :)

**Pull request merged**
