### PR TITLE
Notify upon hex file change

### LINKED ISSUE #22: Combine flash-when-ready and flash now buttons?
The flash button could change text to say "flash when ready"

### LINKED ISSUE #25: Detect when the open hex file has changed, and offer to reflash
Inspired by Notepad++

### PR DESCRIPTION
**Pull request by ItsHarper**
This PR moves a few files, a couple of which GitHub unfortunately isn't showing as moves, so you can't properly see the diffs. [Here's the diff for index.html](http://www.mergely.com/ei08lhHV/) and [the diff for main.js.](http://www.mergely.com/LFRQ67Ze/)

### Changes
* **Merged the flash and flash-when-ready buttons**
Closes #22.
* **Made the app display a dialog box when the selected hex file changes**
Closes #25. Uses the [Bootbox.js](https://github.com/makeusabrew/bootbox) and [chokidar](https://github.com/paulmillr/chokidar) libraries. The Windows taskbar icon will also flash orange and the Mac dock icon will also bounce.
* **Added a gear menu in the bottom left of the window**
Because this menu needs to extend outside of the window's boundaries for it to live in that location, I opted to open a second BrowserWindow. Acceptable performance was achieved by rendering the second window only once, upon app launch, and showing or hiding it as appropriate from there. I'm very surprised at how well that turned out. The only issue is that the main window is defocused when the menu is opened, but it's pretty subtle if your eyes are focused on the bottom left corner.
    * **Added an options modal**
Options are stored using the [electron-settings](https://github.com/nathanbuchar/electron-settings) module, which will save the settings in JSON format in an appropriate place on all operating systems. For now, the only option is whether or not to bring the window to the front when the hex file changes. It is fully functional. On Mac, the default is not to bring to the front. On other platforms, the default is to bring to the front.
    * **Added an about modal**
Currently this just displays the version. After this gets merged we can make a new issue for adding the open source licenses there too. 
* **Reorganized source files a bit**
The top level of the repository is cleaner, and all source code lives in the `src` folder. In the future, I'd like to break up app.js more, and the new structure will allow for sensible placement of additional source files. 
* **Replaced all uses of `var` with either `let` or `const`, as per ES6 best practices**
* **Included [Devtron](http://electron.atom.io/devtron/) in the dev dependencies**
It would have been useful before, but it's even more useful now that we're directly using IPC messages.
* **Switched to obtaining jQuery via npm**

### Screenshots
The bootbox version of the prompt
image

The macOS version of the prompt. I don't really like how it looks with the current icon. I think we should try to get a better one soonish. Perhaps we should not use the native Mac sheet until we have an appropriate icon?
image

The about modal
image

The options modal
image

The gear menu
image

### CODE REVIEW

**Comment by ItsHarper** [comment]
IMHO, we're overdue for a new release (0.6.0?).

**Comment by ItsHarper** [comment]
That last commit makes it so that the main window won't appear until it has fully loaded, [as described here](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#using-ready-to-show-event). It does make a noticeable difference.

**Comment by skullydazed** [comment]
Looking good! Thanks for pulling this together.

I'm about to head to the laser cutter, but in a couple days I'll give this a proper checkover and merge it. I think the mac sheet is fine for now, but we should find a better icon and then prepare for a 0.6.0 release.

**Comment by ItsHarper** [comment]
How do you propose finding a better icon? Do you want to ask the OLKB and Clueboard communities to see if anyone wants to help out there? Do you want to take a crack at it yourself?

**Comment by jackhumbert** [comment]
I used a Psi icon in the QMK helper, and was planning on making that the official for QMK - would you want to move forward with that for now?

**Comment by jackhumbert** [comment]
[This might work](http://i.imgur.com/6YAucqJ.png) - it has a little green arrow added for the flasher :)

**Comment by ItsHarper** [comment]
Haha, I was just typing up a reply that suggested adding an arrow. I think it makes more sense for the arrow to point upwards though, since the flasher sends (uploads) the firmware to the keyboard. I think it would be good if we had a less plain looking version in the future, but this is a big improvement for now.

**Comment by skullydazed** [comment]
The arrow is a cute concept. I'm not sure about facing down like that, though. It should either point up or point right and become larger and sorta hide behind the icon.

**Comment by NoahAndrews** [comment]
Good to see we're on the same wavelength on this @skullydazed :)

**Comment by jackhumbert** [comment]
[This good for now?](http://imgur.com/a/A53j2)

**Comment by ItsHarper** [comment]
I don't want to be too picky, so if you don't feel like messing with it any more, or figuring out how to make something that both skully and I are happy with, feel free to disregard. It'll do perfectly fine as-is.

I really like the circle, but I don't care for the giant arrow sticking out the side. I think circle icons are best encompassing pretty much the entire thing (though I think a little badge in the corner if you have one should extend outside a bit). It just looks unbalanced the way it is though.

My opinion is that you should keep the circle, switch the arrow to either up or to the right, and put it back small and in the corner. 

For future reference, you can show a link to a picture inline by adding an exclamation point in front. You can also upload an image by dragging it directly into the comment box.

**Comment by jackhumbert** [comment]
Let's just go with that for now. I'm not too concerned about the arrow direction - people have different perspectives when it comes to flashing, and whether that's uploading or downloading, so to the right made sense to me :)

**Comment by ItsHarper** [comment]
[Mergely for app.js](http://mergely.com/9rguzrGy/)

**Comment by skullydazed** [comment]
I spent some time this morning working on a logo. After some feedback from @NoahAndrews we decided this was the best design so far.

artboard 1

Adding the chip to the logo really draws the arrow down to the chip like the first logo @jackhumbert did.

**Comment by jackhumbert** [comment]
I like the chip idea. Could we make it less busy though? I'm not sure if the arrow is needed if we have the chip. Something like this would be neat:

qmk-ff

**Comment by skullydazed** [comment]
At the sizes we'll be viewing at it's actually less busy. For example here's the icon at 128:

icon_128x128

And here it is at 64:

icon_32x32 2x

Moving to a 2d chip may be a good idea, but let me try adjusting the arrow/logo placement a bit more. I find the simple concept with the 2d chip/logo a little too plain.

**Comment by jackhumbert** [comment]
It'll be 16x16 on most systems won't it? The borders on each item get obscured out at that point. It looks like the Psi would fit in the 3/4 view chip if we take out the arrow (and you don't think it's needed).

**Comment by skullydazed** [comment]
How's this look? I've tried to better balance the arrow, psi, and chip to reduce how busy it is.

128:

screen shot 2017-01-16 at 9 57 47 am

32:

screen shot 2017-01-16 at 9 59 46 am

I think 32 and 128 will be the most common sizes.

**Comment by skullydazed** [comment]
At 16x16 I think including the arrow is important, otherwise it's just a black blob.

screen shot 2017-01-16 at 10 04 09 am
screen shot 2017-01-16 at 10 02 42 am

We can do some more iteration to make the psi more legible. Maybe another color?

**Comment by jackhumbert** [comment]
This is the main use of the icon, right? It looks like the psi is more visible without the arrow.

icons

**Comment by skullydazed** [comment]
On windows, yeah. There's also showing it in explorer windows and the start menu, both of which use larger icons.

On the mac the icon shows up in the dock (anywhere from 32 to 512, depending on how big they've made it.) It's 512 in launch bar and could be anything between those in the Finder.

**Comment by skullydazed** [comment]
How's this look? I think it's pretty legible at 16px but still visually interesting at 128.

screen shot 2017-01-16 at 10 32 51 am

screen shot 2017-01-16 at 10 33 15 am

**Comment by jackhumbert** [comment]
Let's do custom pixel-perfect versions for the 16x16 and 32x32 icons - I can make a more detailed/interesting 2D chip icon for the larger sizes later today if you think that idea will work well. 

The small icon is saying it's 30x30 - is this a limit of Github that's trying to scaling it up?

**Comment by skullydazed** [comment]
It could be that, or it could be something in how I quickly generated that image by zooming Illustrator and taking a screenshot, then cropping. :)

I'm loathe to have the need to maintain multiple files for different sizes, but if that's the compromise that works for everyone I'm on board.

**Comment by jackhumbert** [comment]
:) unfortunately the multiple file sizes are pretty standard for Mac apps like that. In illustrator you can make multiple artboards to keep them in the same file! It's not the best for pixel work like this, though.

**Comment by jackhumbert** [comment]
How are these? I'd really like the psi to be readable at the 16x16 size.

psi-16
psi-32
psi-512

**Comment by ItsHarper** [comment]
Love them.

**Comment by skullydazed** [comment]
Nice! I like it.

**Comment by skullydazed** [comment]
I've got some icon documentation I wrote. Let me commit that so you know what sizes are needed.

**Comment by skullydazed** [comment]
I just committed f06941a41 which tells you what files need to be there to generate a mac icon. You can use https://www.icoconverter.com to create a windows icon with various sizes it seems.

**Pull request merged**
