### PR TITLE
Simple/Expert UI changer

### PR DESCRIPTION
**Pull request by skullydazed**
Opened a new PR because #24 got too complicated after the restructuring.

### CODE REVIEW

**Comment by skullydazed** [comment]
One problem I'm still trying to figure out is why the gear menu opens the menu 200 pixel below the window, rather than inside the window.

**Comment by ItsHarper** [comment]
Right now, the menu opens at a specific position relative to (I believe) the top left corner. It would probably be better to define its position from one of the bottom corners, to avoid issues like this when the window size changes.

**Comment by skullydazed** [comment]
I've rebased this branch off #43. We'll need to merge #43 before this gets merged.

**Comment by skullydazed** [comment]
I'm pretty happy with how this works now. I need to test on windows and in packaged versions, but if it looks good there I'm ready to merge this.

**Pull request merged**
